[build-system]
requires = [
  "setuptools"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "openshift: marks tests as requiring an OpenShift cluster (deselect with '-m \"not openshift\"')",
]

[tool.black]
line-length = 160
target-version = ['py312']
include = '(src|tests)/.*\.py$'
