name: Build Documentation

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  release:
    types: [ published ]

# Ensure only one build at a time for any branch, cancelling any in-progress builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install package and doc build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"

      - name: Build documentation
        run: |
          mkdocs build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        if: ${{ github.event_name == 'release' || contains(github.event.head_commit.message, '[doc]') }}
        with:
          branch: gh-pages
          folder: site
